services:

#  experiment-fedproxy:
#    hostname: fedproxy
#    image: davidedomini99/experiments-2025-iot-self-fl:latest
#    volumes:
#      - davide.domini-volume:/data
#    environment:
#      DATA_OWNER: 1000:1000
#      LEARNING_HYPERPARAMETERS: |
#        fedproxy:
#          areas: [3, 5, 9]
#
#  experiment-scaffold:
#    hostname: scaffold
#    image: davidedomini99/experiments-2025-iot-self-fl:latest
#    volumes:
#      - davide.domini-volume:/data
#    environment:
#      DATA_OWNER: 1000:1000
#      LEARNING_HYPERPARAMETERS: |
#        scaffold:
#          areas: [3, 5, 9]

  experiment-ifca-areas-3:
    hostname: ifca-areas-3
    image: davidedomini99/experiments-2025-iot-self-fl:1.0.8
    volumes:
      - davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        ifca: 
          areas: [3]

  experiment-ifca-areas-5:
    hostname: ifca-areas-5
    image: davidedomini99/experiments-2025-iot-self-fl:1.0.8
    volumes:
      - davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        ifca: 
          areas: [5]
          
  experiment-ifca-areas-9:
    hostname: ifca-areas-9
    image: davidedomini99/experiments-2025-iot-self-fl:1.0.8
    volumes:
      - davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        ifca: 
          areas: [9]

volumes:
  davide.domini-volume:
    external: true