services:

  experiment-fedproxy:
    hostname: fedproxy
    image: davidedomini/experiments-2025-iot-self-fl:latest
    volumes:
      - ./davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        fedproxy: 
          areas: [3, 5, 9]

  experiment-scaffold:
    hostname: scaffold
    image: davidedomini/experiments-2025-iot-self-fl:latest
    volumes:
      - ./davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        scaffold: 
          areas: [3, 5, 9]