services:

  experiment-fedproxy:
    hostname: fedproxy
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    volumes:
      - ./davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        fedproxy: 
          areas: [3, 5, 9]

  experiment-scaffold:
    hostname: scaffold
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    volumes:
      - ./davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        scaffold: 
          areas: [3, 5, 9]